{% set name = "pydata-sphinx-theme" %}
{% set version = "0.6.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 32e0580ef985734d652eec2bf25e0995a330a9d4f76deaa353571ce8e180ab14
  - folder: src
    url: https://github.com/pydata/pydata-sphinx-theme/archive/refs/tags/v{{ version }}.tar.gz
    sha256: c5e33c92ab3524327b7f07b46768d4765124101ea6112379755cc72e050b49d8

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - sphinx
    - beautifulsoup4
    - docutils <0.17

test:
  source_files:
    - src/tests
  imports:
    - pydata_sphinx_theme
  commands:
    - pip check
    - cd src/tests
    - pytest -vv --cov pydata_sphinx_theme --cov-branch --cov-fail-under=73 --cov-report term-missing:skip-covered --no-cov-on-fail
  requires:
    - jupyter_sphinx !=0.3.1
    - numpydoc
    - pandas
    - pip
    - plotly
    - pytest-cov
    - pytest-regressions
    - recommonmark
    - sphinx-thebe
    - xarray

about:
  home: https://github.com/pydata/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE
  summary: Bootstrap-based Sphinx theme from the PyData community
  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
    - bollwyvl
