{% set version = "0.17.0" %}
{% set python_min = python_min | default("3.9") %}

{% set min_sphinx = "6.1" %}

package:
  name: pydata-sphinx-theme
  version: {{ version }}

source:
  - url: https://pypi.org/packages/py3/p/pydata-sphinx-theme/pydata_sphinx_theme-{{ version }}-py3-none-any.whl
    sha256: cec5c92f41f4a11541b6df8210c446b4aa9c3badb7fcf2db7893405b786d5c99
  - folder: src
    url: https://github.com/pydata/pydata-sphinx-theme/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 750cb543afb61e52bbd5c41b7b252194d2228a626eab2e49aba64e99f4b6f263

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --find-links . --no-index --ignore-installed --no-deps pydata-sphinx-theme
    - cd {{ RECIPE_DIR }} && {{ PYTHON }} collect_licenses.py

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - sphinx-theme-builder >=0.2.0a7
  run:
    - accessible-pygments
    - babel
    - beautifulsoup4
    - docutils !=0.17.0
    - pygments >=2.7
    - python >={{ python_min }}
    - sphinx >={{ min_sphinx }}
    - typing_extensions

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-cov
    - pytest-regressions
    - python {{ python_min }}
    - sphinx {{ min_sphinx }}.*
  imports:
    - pydata_sphinx_theme
  commands:
    - pip check
    # tests in run_test.py

about:
  home: https://github.com/pydata/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - src/LICENSE
    - third-party-licenses/
  summary: Bootstrap-based Sphinx theme from the PyData community
  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
    - bollwyvl
    - michaelweinold
