{% set version = "0.15.3" %}
{% set cov_fail_under = "88" %}
{% set min_sphinx = "5.0" %}

package:
  name: pydata-sphinx-theme
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py3/p/pydata-sphinx-theme/pydata_sphinx_theme-{{ version }}-py3-none-any.whl
    sha256: a48ee049dc9b0f7064dbb8f7064b1cf3ae48aa193faafe14abd403a1b7102810
  - folder: src
    url: https://github.com/pydata/pydata-sphinx-theme/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 93d2e10766d6f6697e3b23eccf4b8a81f87e48e321688c2bc07bba5b996a8e4b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --find-links . --no-index --ignore-installed --no-deps pydata-sphinx-theme
    - cd {{ RECIPE_DIR }} && {{ PYTHON }} collect_licenses.py

requirements:
  host:
    - pip
    - python >=3.9
    - sphinx-theme-builder >=0.2.0a7
  run:
    - accessible-pygments
    - babel
    - beautifulsoup4
    - docutils !=0.17.0
    - packaging
    - pygments >=2.7
    - python >=3.9
    - sphinx >={{ min_sphinx }}
    - typing_extensions

test:
  source_files:
    - src/tests
  imports:
    - pydata_sphinx_theme
  commands:
    - pip check
    - cd src/tests
    - pytest -vv --cov=pydata_sphinx_theme --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under={{ cov_fail_under }}
  requires:
    - sphinx {{ min_sphinx }}.*
    - jupyter_sphinx
    # numpydoc 1.7 requires sphinx 6
    - numpydoc <1.7
    - pandas
    - pip
    - plotly
    - pytest-cov
    - pytest-regressions
    - recommonmark
    - sphinx-thebe
    - xarray

about:
  home: https://github.com/pydata/pydata-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - src/LICENSE
    - third-party-licenses/font-awesome-LICENSE.txt
  summary: Bootstrap-based Sphinx theme from the PyData community
  doc_url: https://pydata-sphinx-theme.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-sphinx-theme

extra:
  recipe-maintainers:
    - jorisvandenbossche
    - bollwyvl
    - michaelweinold
